# Generated by Django 5.0.7 on 2024-10-18 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='row',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
