# Generated by Django 5.1.2 on 2024-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_exam_course_id_alter_exam_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='room_number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='exam',
            name='row',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='section_id',
            field=models.CharField(max_length=64),
        ),
    ]
